discrete_inter_dist.sh HI LV
discrete_inter_dist.sh HI RU
discrete_inter_dist.sh HI CB
discrete_inter_dist.sh HI KO
discrete_inter_dist.sh HI FD
discrete_inter_dist.sh HI PC
discrete_inter_dist.sh HI SA
discrete_inter_dist.sh HI CR
discrete_inter_dist.sh HI MQ
discrete_inter_dist.sh HI SO
discrete_inter_dist.sh LV RU
discrete_inter_dist.sh LV CB
discrete_inter_dist.sh LV KO
discrete_inter_dist.sh LV FD
discrete_inter_dist.sh LV PC
discrete_inter_dist.sh LV SA
discrete_inter_dist.sh LV CR
discrete_inter_dist.sh LV MQ
discrete_inter_dist.sh LV SO
discrete_inter_dist.sh RU CB
discrete_inter_dist.sh RU KO
discrete_inter_dist.sh RU FD
discrete_inter_dist.sh RU PC
discrete_inter_dist.sh RU SA
discrete_inter_dist.sh RU CR
discrete_inter_dist.sh RU MQ
discrete_inter_dist.sh RU SO
discrete_inter_dist.sh CB KO
discrete_inter_dist.sh CB FD
discrete_inter_dist.sh CB PC
discrete_inter_dist.sh CB SA
discrete_inter_dist.sh CB CR
discrete_inter_dist.sh CB MQ
discrete_inter_dist.sh CB SO
discrete_inter_dist.sh KO FD
discrete_inter_dist.sh KO PC
discrete_inter_dist.sh KO SA
discrete_inter_dist.sh KO CR
discrete_inter_dist.sh KO MQ
discrete_inter_dist.sh KO SO
discrete_inter_dist.sh FD PC
discrete_inter_dist.sh FD SA
discrete_inter_dist.sh FD CR
discrete_inter_dist.sh FD MQ
discrete_inter_dist.sh FD SO
discrete_inter_dist.sh PC SA
discrete_inter_dist.sh PC CR
discrete_inter_dist.sh PC MQ
discrete_inter_dist.sh PC SO
discrete_inter_dist.sh SA CR
discrete_inter_dist.sh SA MQ
discrete_inter_dist.sh SA SO
discrete_inter_dist.sh CR MQ
discrete_inter_dist.sh CR SO
discrete_inter_dist.sh MQ SO
